- app/controllers/articles_controller.rb
- app/models/article.rb
- app/models/user.rb
- app/views/articles/index.html.erb
- app/views/pages/home.html.erb
- config/routes.rb
- test/controllers/articles_controller_test.rb
create articles controller and its views, according to db creation of article db, added methods to move on the project
> create articles controller and its views

- app/controllers/articles_controller.rb
skip login for articles all page
> skip login for articles all page

- app/models/article.rb
- app/models/user.rb
> minor changes

- config/routes.rb
- db/migrate/20230622151116_create_active_storage_tables.active_storage.rb
- db/schema.rb
fix destroy and added active store migration
> fix destroy and added active store migration

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
added img and text align first steps
added shadow to image and text, start styling of first page
> added img and text align first steps

- Gemfile
- Gemfile.lock
> removed rails live reload

- app/assets/stylesheets/components/_actiontext.scss
- app/assets/stylesheets/components/_articles.scss
- app/assets/stylesheets/components/_index.scss
- app/views/articles/_form.html.erb
- app/views/articles/index.html.erb
- app/views/articles/show.html.erb
- app/views/layouts/application.html.erb
melhorando a cara do articles
Custumizando o clodinary resources para mostrar as imagens em 400 x 400.
> melhorando a cara do articles

- .gitignore
- package.json
- yarn.lock
> fix errors

- app/assets/stylesheets/pages/_home.scss
- app/controllers/articles_controller.rb
- app/controllers/pages_controller.rb
- app/javascript/controllers/index.js
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
try to add images to home slideshow
> try to add images to home slideshow

- app/views/pages/home.html.erb
> add carousel working

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> carousel evolving

- app/views/pages/home.html.erb
fix carousel error depois do commit
> fix carousel error depois do commit

- app/assets/stylesheets/pages/_privacy.scss
- app/views/pages/contact.html.erb
- app/views/pages/privacy.html.erb
> fixed color font provacy

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> fixed footer

- app/assets/stylesheets/components/_articles.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/articles/_form.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
> fixed things general

- app/assets/stylesheets/pages/_institute.scss
- app/views/pages/institute.html.erb
> fixing css

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Start fix home, hallyza cards, body height etc
> Start fix home, hallyza cards, body height etc

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> Fix card + card text overlay

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
start media query responsivity
> start media query responsivity

- app/assets/stylesheets/pages/_home.scss
> fix one css

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> comecando resposividade

- Gemfile
- Gemfile.lock
- config/initializers/rails_live_reload.rb
> rails_live_reload

- app/assets/stylesheets/pages/_carousel.scss
- app/assets/stylesheets/pages/_contact.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/articles/_mudar_coisas.html
- app/views/articles/index.html.erb
- app/views/articles/show.html.erb
- app/views/pages/contact.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
media queries desktop screens done
> media queries desktop screens done

- app/assets/config/manifest.js
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
finalizado resposividade do cartoa inicial
> finalizado resposividade do cartoa inicial

- app/assets/stylesheets/components/_articles.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_carousel.scss
- app/views/articles/index.html.erb
- app/views/pages/home.html.erb
Removido do carousel e dos artigos
> Removido underline azul

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
mudanca de cartao para novo estilo
> mudanca de cartao para novo estilo

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
adicionada cor no texto cartao
> adicionada cor no texto cartao

- app/assets/stylesheets/components/_articles.scss
- app/assets/stylesheets/pages/_carousel.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/articles/index.html.erb
- app/views/pages/home.html.erb
- config/environments/development.rb
Fiz a responsividade das especializacoes da homepage
> Responsividade homepage

- app/assets/stylesheets/pages/_institute.scss
- app/views/layouts/application.html.erb
- app/views/pages/institute.html.erb
instituto e responsividade okai
> instituto e responsividade okai

- app/assets/stylesheets/components/_articles.scss
- app/assets/stylesheets/pages/_carousel.scss
- app/views/articles/index.html.erb
- app/views/articles/show.html.erb
- app/views/pages/home.html.erb
Mudanças realizadas na pagina de artigo
> Mudanças realizadas na pagina de artigo

- app/assets/stylesheets/components/_articles.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_new.scss
- app/views/articles/_form.html.erb
- app/views/articles/index.html.erb
- app/views/articles/new.html.erb
- app/views/articles/show.html.erb
Responsividade de artigo, artigos, criar artigo, foram realizadas
> Artigo e Artigos, Criar Artigo

- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_sessions.scss
- app/javascript/controllers/alert_controller.js
- app/javascript/controllers/index.js
- app/views/devise/sessions/new.html.erb
- app/views/shared/_flashes.html.erb
- config/locales/devise.en.yml
- config/routes.rb
Adicionado SEO, favicon etc
Adicionado js controller para sumir com sign in, 
Removida sign in
adicionado seeds
> setup toques finais primeira parte

- app/assets/stylesheets/components/_articles.scss
- app/javascript/classes/RichText.js
- app/javascript/controllers/emoji_picker_controller.js
- app/javascript/controllers/index.js
- app/views/articles/_form.html.erb
- package.json
- yarn.lock
> projeto Hallyza finalizado

- app/views/pages/specialties.html.erb
texto de especialidades adicionado
> texto de especialidades adicionado

- app/views/pages/contact.html.erb
> celular mudado em contato

- app/assets/stylesheets/pages/_home.scss
- app/javascript/controllers/index.js
- app/javascript/controllers/scroll_reveal_controller.js
- app/views/pages/home.html.erb
> add stimulus agendamento home

- app/assets/stylesheets/components/articles/_articles-show.scss
fix media queries for trix editor
> fix media queries for trix editor

- app/controllers/pages_controller.rb
> articles home somente 3

- app/assets/stylesheets/components/articles/_articles-show.scss
- app/assets/stylesheets/pages/homepage/_home__card.scss
- db/seeds.rb
start prepare for production 3
mudancas em:
_articles-show:
.custom-card img {
width: 100%;
object-fit: cover;
border-radius: 20px 20px 0 0;
}
_home__card:
.card-hallyza {
display: flex;
flex-direction: row;
flex-wrap: wrap;
justify-content: center; >> estava space-evenly
}
Seeda:
Remover primeiro hallyza
> start prepare for production 3

- app/assets/stylesheets/components/articles/_articles-index.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_contact.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_institute.scss
- app/assets/stylesheets/pages/_specialties.scss
- app/assets/stylesheets/pages/homepage/_home__card.scss
- app/assets/stylesheets/pages/homepage/_home__especialides.scss
- app/views/pages/home.html.erb
trocando fontes
de IBM Plex mono sans serif para Arapey serif
> trocando fontes

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/pages/_institute.scss
- app/views/pages/contact.html.erb
- app/views/pages/home.html.erb
- app/views/pages/institute.html.erb
- app/views/shared/_navbar.html.erb
mudanças realizadas de acordo com pedido 1
> mudanças realizadas de acordo com pedido 1

- app/views/pages/institute.html.erb
mudanças realizadas de acordo com pedido 2
> mudanças realizadas de acordo com pedido 2
